### ISSUE TITLE
DBpedia Import in die Cassandra

### ISSUE THREAD

**Issue by nstrelow** [bpn1/ingestion#3]
# Tasks
## DBpediaRDD
- [x] Concatenate and clean DBpedia .ttl dumps
- [x] Parse the created .ttl dump
- [ ] Replace uris with prefixes
- [x] Convert to `case class DBpediaEntity`
## Deduplikation
- [ ] Join RDDs on sameAs.wikidata:Qxxxxx or wikipageId
## DataLakeImport
- [ ] Translate case class DBpediaEntitiy to case class Subject
